---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-k8s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: local-k8s
  source:
    repoURL: https://github.com/jasondewitt/local-k8s.git
    targetRevision: HEAD
    path: local-k8s
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true