apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: traefik

spec:
  rules:
    - host: plex.internal
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  plex
                port:
                  number: 32400
