apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  routes:
  - match: Host(`plex.internal`)
    kind: Rule
    services:
    - name: plex
      kind: service
      namespace: traefik
      port: 32400



