apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-dashboard
  namespace: traefik
spec:
  entrypoints:
  - web
  routes:
  - match: Host(`plex.internal`)
    kind: Rule
    services:
    - name: plex
      kind: Service
      namespace: plex
      port: 32400



