apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v6.29.2 
    helm:
      releaseName: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    syncOptions:
    - CreateNamespace=true