apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: local-k8s
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v2.11.1 
    helm:
      releaseName: loki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    syncOptions:
    - CreateNamespace=true