apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v0.48.3 
    helm:
      releaseName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    syncOptions:
    - CreateNamespace=true