apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: local-k8s
  source:
    repoURL: https://github.com/jasondewitt/local-k8s.git
    targetRevision: HEAD
    path: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
