apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: v10.19.5
    helm:
      releaseName: traefik
      values: |
        service:
          enabled: true
          type: LoadBalancer
          spec:
            loadBalancerIP: 10.0.0.225

        logs:
          access:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    syncOptions:
    - CreateNamespace=true